### PR TITLE
Add Covid Stats dashboard to showcase README

### PR DESCRIPTION
**Pull request by arisp**

### CODE REVIEW

**Comment by puf17640** [comment]
actually meant to request changes instead of approving

**Comment by arisp** [comment]
@puf17640 thanks for the feedback. Will address.

Are you sure the page is not loading for you though? Seems to work for me (even though my API server doesn't have a valid cert yet).

**Comment by puf17640** [comment]
@arisp are you going to update your PR ?

**Comment by arisp** [comment]
@puf17640 site fixed and PR updated

**Comment by puf17640** [comment]
Thanks!

**Pull request merged**
