### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by suraj-deshmukh**
added covid19 tracker dashboard details in Dashboard section

### CODE REVIEW

**Comment by puf17640** [comment]
image
commas look weird, please fix this 😄

**Comment by suraj-deshmukh** [comment]
@puf17640 whats wrong in it????

**Comment by puf17640** [comment]
it's not how they look, the placement is wrong.
40,26,993 should actually be 4,026,993

**Comment by suraj-deshmukh** [comment]
fixed it.

Screenshot from 2020-05-10 07-54-58

**Comment by puf17640** [comment]
cool!

**Pull request merged**
